import { jsPDF } from "jspdf";

const generatePDF = (trip) => {

    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(13, 110, 253);
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);

    doc.text("AI Travel Planner", pageWidth / 2, 18, {
        align: "center",
    });

    // Title
    doc.setTextColor(0, 0, 0);

    doc.setFontSize(18);

    doc.text(
        trip.title || "Travel Itinerary",
        15,
        42
    );

    // Date

    doc.setFontSize(11);

    doc.setTextColor(120);

    doc.text(
        `Created: ${new Date(
            trip.createdAt
        ).toLocaleString()}`,
        15,
        50
    );

    // Line

    doc.setDrawColor(220);

    doc.line(15, 56, 195, 56);

    // Itinerary

    doc.setTextColor(30);

    doc.setFontSize(12);

    const lines = doc.splitTextToSize(
        trip.itinerary,
        180
    );

    let y = 66;

    const pageHeight =
        doc.internal.pageSize.height;

    lines.forEach((line) => {

        if (y > pageHeight - 20) {

            doc.addPage();

            y = 20;

        }

        doc.text(line, 15, y);

        y += 7;

    });

    // Footer

    const totalPages = doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {

        doc.setPage(i);

        doc.setFontSize(10);

        doc.setTextColor(150);

        doc.text(
            `Generated by AI Travel Planner`,
            pageWidth / 2,
            288,
            {
                align: "center",
            }
        );

        doc.text(
            `Page ${i} / ${totalPages}`,
            190,
            288,
            {
                align: "right",
            }
        );

    }

    doc.save(
        `${trip.title || "Travel-Itinerary"}.pdf`
    );

};

export default generatePDF;